import Foundation
import OSLog
import ReolinkAPI
#if canImport(FoundationModels)
import FoundationModels
#endif

private let log = Logger(subsystem: "com.reolens.app", category: "event-summarizer")

/// 0.5.1 — Produces a short "what happened today" summary across the
/// hub's recordings using Apple's on-device FoundationModels framework
/// when available (iOS 26 / macOS 26 + Apple Intelligence), with a
/// deterministic count-based fallback otherwise.
///
/// All inference is on-device — there is no network call. Inputs are
/// the day's `SearchFile`s grouped by camera and the user's per-camera
/// labels; output is a one-line headline + 1–3 bullet points.
public actor EventSummarizer {
    public static let shared = EventSummarizer()

    public struct CameraSummary: Sendable, Hashable {
        public let cameraID: UUID
        public let cameraName: String
        public let totalClips: Int
        public let triggers: [DetectionType: Int]

        public init(
            cameraID: UUID,
            cameraName: String,
            totalClips: Int,
            triggers: [DetectionType: Int]
        ) {
            self.cameraID = cameraID
            self.cameraName = cameraName
            self.totalClips = totalClips
            self.triggers = triggers
        }
    }

    public struct DailyDigest: Sendable, Hashable {
        public let headline: String
        public let bulletPoints: [String]
        public let source: Source

        public enum Source: String, Sendable, Hashable {
            /// Generated by FoundationModels on-device.
            case foundationModels
            /// Deterministic count-based fallback (no Apple
            /// Intelligence on this device, or FM session refused).
            case fallback
        }

        public init(headline: String, bulletPoints: [String], source: Source) {
            self.headline = headline
            self.bulletPoints = bulletPoints
            self.source = source
        }
    }

    /// Cache key — a digest is stable as long as the inputs are stable.
    private struct CacheKey: Hashable {
        let day: Date
        let cameraIDs: [UUID]
        let totalClips: Int
    }

    private var cache: [CacheKey: DailyDigest] = [:]

    public init() {}

    /// Produce a digest for the given day's recordings, grouped by
    /// camera. Re-uses a cached result when the same set of inputs has
    /// been summarized before. Always returns a value — the fallback
    /// path never throws.
    public func summarize(
        day: Date,
        perCamera: [CameraSummary]
    ) async -> DailyDigest {
        let key = CacheKey(
            day: Calendar.current.startOfDay(for: day),
            cameraIDs: perCamera.map(\.cameraID).sorted(),
            totalClips: perCamera.reduce(0) { $0 + $1.totalClips }
        )
        if let hit = cache[key] { return hit }

        let digest: DailyDigest
        #if canImport(FoundationModels)
        if let fm = await foundationModelsDigest(perCamera: perCamera) {
            digest = fm
        } else {
            digest = fallbackDigest(perCamera: perCamera)
        }
        #else
        digest = fallbackDigest(perCamera: perCamera)
        #endif

        cache[key] = digest
        return digest
    }

    public func clearCache() { cache.removeAll() }

    // MARK: - Foundation Models path

    #if canImport(FoundationModels)
    @available(iOS 26.0, macOS 26.0, *)
    @Generable
    struct FMDigest {
        @Guide(description: "A single short headline summarizing the day across all cameras. Max 70 characters.")
        let headline: String
        @Guide(description: "1 to 3 short bullet points highlighting the most notable activity. Each under 80 characters.")
        let bullets: [String]
    }

    private func foundationModelsDigest(perCamera: [CameraSummary]) async -> DailyDigest? {
        guard #available(iOS 26.0, macOS 26.0, *) else { return nil }
        let model = SystemLanguageModel.default
        guard case .available = model.availability else {
            log.info("FoundationModels unavailable; using fallback summary.")
            return nil
        }
        let prompt = buildPrompt(perCamera: perCamera)
        do {
            let session = LanguageModelSession(model: model)
            let response = try await session.respond(
                to: prompt,
                generating: FMDigest.self
            )
            return DailyDigest(
                headline: response.content.headline,
                bulletPoints: response.content.bullets,
                source: .foundationModels
            )
        } catch {
            log.warning("FoundationModels digest failed: \(String(describing: error), privacy: .public)")
            return nil
        }
    }

    private func buildPrompt(perCamera: [CameraSummary]) -> String {
        var lines: [String] = []
        lines.append("Summarize today's home camera activity in plain English. Be concise and neutral; no alarmist language.")
        lines.append("")
        for cam in perCamera where cam.totalClips > 0 {
            let triggerSummary = cam.triggers
                .sorted { $0.value > $1.value }
                .map { "\($0.value) \($0.key.label.lowercased())" }
                .joined(separator: ", ")
            if triggerSummary.isEmpty {
                lines.append("- \(cam.cameraName): \(cam.totalClips) clips, no AI detections.")
            } else {
                lines.append("- \(cam.cameraName): \(cam.totalClips) clips — \(triggerSummary).")
            }
        }
        return lines.joined(separator: "\n")
    }
    #endif

    // MARK: - Fallback path

    /// `internal` + `nonisolated` so tests can exercise the
    /// deterministic fallback without depending on whether the test
    /// machine has Apple Intelligence available.
    nonisolated func fallbackDigest(perCamera: [CameraSummary]) -> DailyDigest {
        let totalClips = perCamera.reduce(0) { $0 + $1.totalClips }
        guard totalClips > 0 else {
            return DailyDigest(
                headline: "No activity today.",
                bulletPoints: [],
                source: .fallback
            )
        }
        var triggerTotals: [DetectionType: Int] = [:]
        for cam in perCamera {
            for (k, v) in cam.triggers {
                triggerTotals[k, default: 0] += v
            }
        }
        let topTriggers = triggerTotals
            .sorted { $0.value > $1.value }
            .prefix(3)
            .map { "\($0.value) \($0.key.label.lowercased())" }
        let headline: String = {
            if topTriggers.isEmpty {
                return "\(totalClips) clip\(totalClips == 1 ? "" : "s") today."
            }
            return "\(totalClips) clip\(totalClips == 1 ? "" : "s") today: " + topTriggers.joined(separator: ", ") + "."
        }()
        let busiest = perCamera
            .filter { $0.totalClips > 0 }
            .sorted { $0.totalClips > $1.totalClips }
            .prefix(3)
            .map { "\($0.cameraName): \($0.totalClips)" }
        return DailyDigest(
            headline: headline,
            bulletPoints: busiest,
            source: .fallback
        )
    }
}
